//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDWITHEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_master
    {
        public int id { get; set; }
        public int empcode { get; set; }
        public string empname { get; set; }
        public string designation { get; set; }
        public int salary { get; set; }
    }
}
